### PR TITLE
try to fix calculate output error in depth_first_visit

### PR DESCRIPTION
**Pull request by zywbuptsse**

### CODE REVIEW

**Comment by yhirose** [comment]
@zywbuptsse, thanks for the pull request, but I would not like to include the current keywords.txt in this pull request since it seems to contain lots of sensitive data... Could you make another smallest possible data file without any sensitive information to reproduce this problem? Thanks!

**Comment by yhirose** [comment]
I also temporarily disabled your unit test and run the test suite with your change in fstlib.h. But it breaks one of unit tests...

```
[zywbuptsse-master] ~/Projects/cpp-fstlib/build$ ctest --rerun-failed --output-on-failure
Test project /Users/yhirose/Projects/cpp-fstlib/build
    Start 33: ReadmeTest.General
1/1 Test #33: ReadmeTest.General ...............***Failed    0.01 sec
Running main() from /Users/yhirose/Projects/cpp-fstlib/build/_deps/googletest-src/googletest/src/gtest_main.cc
Note: Google Test filter = ReadmeTest.General
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ReadmeTest
[ RUN      ] ReadmeTest.General
/Users/yhirose/Projects/cpp-fstlib/test/test.cc:830: Failure
Expected equality of these values:
  u8"こんにちは"
    Which is: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF"
    As Text: "こんにちは"
  o
    Which is: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF!"
    As Text: "こんにちは!"
/Users/yhirose/Projects/cpp-fstlib/test/test.cc:855: Failure
Expected equality of these values:
  u8"こんにちは"
    Which is: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF"
    As Text: "こんにちは"
  o
    Which is: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF!"
    As Text: "こんにちは!"
/Users/yhirose/Projects/cpp-fstlib/test/test.cc:866: Failure
Expected equality of these values:
  u8"こんにちは"
    Which is: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF"
    As Text: "こんにちは"
  o
    Which is: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF!"
    As Text: "こんにちは!"
[  FAILED  ] ReadmeTest.General (1 ms)
[----------] 1 test from ReadmeTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ReadmeTest.General

 1 FAILED TEST
```

**Comment by zywbuptsse** [comment]
well, I check my case again, it turns out my test data has duplicated in lines...it's not a bug

**Comment by zywbuptsse** [comment]
I will close this PR, thanks for your time.

**Pull request closed without merging**
